# ===============================
# APP INFO
# ===============================


spring.application.name=foodies_backend
server.port=9091

# ===============================
# MONGODB CONFIG
# ===============================
#spring.data.mongodb.uri=mongodb://localhost:27017/foodies 
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# ===============================
# AWS S3 CONFIG
# ===============================
aws.access.key=${AWS_ACCESS_KEY_ID}
aws.secret.key=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.s3.bucketname=${AWS_S3_BUCKET}

# ===============================
# PAYSTACK CONFIG
# ===============================
paystack.public.key=${PAYSTACK_PUBLIC_KEY}
paystack.secret.key=${PAYSTACK_SECRET_KEY}
paystack.base.url=${PAYSTACK_BASE_URL}

# ===============================
# JWT CONFIG
# ===============================
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration=${JWT_EXPIRATION}

# ===============================
# MAIL CONFIG
# ===============================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS}

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.com.example.foodies_backend=DEBUG

# ===============================
# DEVTOOLS
# ===============================
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# ===============================
# JACKSON (JSON FORMAT)
# ===============================
spring.jackson.serialization.indent_output=true

# ===============================
# FILE UPLOAD LIMITS
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# CACHE (HAZELCAST)
# ===============================
spring.cache.type=hazelcast

# ===============================
# SERVER ERROR HANDLING
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always

spring.main.allow-bean-definition-overriding=true